# Use this file to easily define all of your cron jobs.
#
# It's helpful, but not entirely necessary to understand cron before proceeding.
# http://en.wikipedia.org/wiki/Cron

# Learn more: http://github.com/javan/whenever

# uncomment line below to set log file
# set :output, "log/cron.log"


# WHENEVER GEM TERMINAL COMMANDS

# set a user as which to install the crontab: "whenever --user some_user"

# add to job to crontab: "whenever --update-crontab"
# If you run the whenever --update-crontab without passing the --user attribute,
# cron will be generated by the current user. This mean tasks that needs other user
# permission will fail.

# remove tasks from crontab: "whenever --clear-crontab"
# see scheduled cron jobs: "crontab -l"

# JOBS

every 1.day, at: "12:05 am" do
  rake "name_days:update_celebration_status"
end
